// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagementSystem.Data;

#nullable disable

namespace VisitorManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorManagementSystem.Models.HomePageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("VisitorManagementSystem.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorMilitaryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Job = "رئيس فرع النظم",
                            Purpose = "سري",
                            Rank = "نقيب",
                            RequestTime = new DateTime(2025, 7, 13, 12, 1, 34, 760, DateTimeKind.Utc).AddTicks(1210),
                            Status = "Pending",
                            VisitorMilitaryID = "",
                            VisitorName = "اسلام محمود محمد"
                        },
                        new
                        {
                            Id = 2,
                            Job = "رئيس فرع التجنيد",
                            Purpose = "طلبية يوليو",
                            Rank = "عقيد",
                            RequestTime = new DateTime(2025, 7, 13, 12, 1, 34, 760, DateTimeKind.Utc).AddTicks(1213),
                            Status = "Pending",
                            VisitorMilitaryID = "",
                            VisitorName = "محمود القناوي"
                        },
                        new
                        {
                            Id = 3,
                            Job = "رئيس فرع المجمع",
                            Purpose = "سري",
                            Rank = "نقيب",
                            RequestTime = new DateTime(2025, 7, 13, 12, 1, 34, 760, DateTimeKind.Utc).AddTicks(1215),
                            Status = "Pending",
                            VisitorMilitaryID = "",
                            VisitorName = "محمود نزية"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
